# Python Review

Short review about some core concepts in python expemplified by objects in the numpy library.

Goals:
- recall basic python vocabulary
- practice markdown syntax
    
## Libraries and Packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files

**NumPy:**

- core library for numerical computing in PYthon
- many of libraries use NumPy arraysas their building blocks
- computations on NumPy objectd are optomized for speed and memory usage

Let's Import NumPy with its **standard abbreviation `np`:**

In [2]:
import numpy as np

## Variables

**variables:** a name we assign to a particular object in Python

Example:

In [5]:
# Assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our jupiter notebook:

In [7]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [8]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
