# Python Review

Short review about some core concepts in python expemplified by objects in the numpy library.

Goals:
- recall basic python vocabulary
- practice markdown syntax
    
## Libraries and Packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files

**NumPy:**

- core library for numerical computing in PYthon
- many of libraries use NumPy arraysas their building blocks
- computations on NumPy objectd are optomized for speed and memory usage

Let's Import NumPy with its **standard abbreviation `np`:**

In [1]:
import numpy as np

## Variables

**variables:** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our jupiter notebook:

In [3]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake case` for naming variables

This is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `myVariable`...
PEP 8 - Style guide for PYthon Code recommends snake_case.
Consistent throughout code = looks more professional

**Variable names should be both descriptive and precise**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables. (ex sun = sol (Spanish) or soleil (French))

In practice, we can often use the word variable and object interchangeably. 


## Types

Every object in Python has a **type**, which tells us what kind of object we have.
We can also call the type of an object, the **class** of an object. So class and object both mean what kind of object we have.

In [8]:
print(a)

[[1 1 2]
 [3 5 8]]


In [11]:
# See the type/class of a variable using the `type` function
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/data type of the NumPy package

In [15]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer type `int`.

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number

Check-in: access the value 5 in array `a`
(like displacement! if displacement = 0, are at first position)

In [18]:
print(a[1,1])

5


## Functions

`print` was our first example of a Python **function**

Functions take place in a set of **arguments**, separated by commas, and use those arguments to create an **output**.
In this course we will be using argument and parameter interchangeably, but they do have slightly different meanings.

We can ask for information about what a function does by executing ? followed by the function name

In [20]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is called **docstring**, a special type of comment that is used to document how a function (or a class, or module) works.

Notice that there are different types of arguments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:
- **non-optional**: arguments *you* have to specify for the function to work
- **optional**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`

Example:
`end` is a parameter in the `print` with default value in the new line
We can pass the value `:-)` to this parameter so that it finishes with `:-)` instead

In [22]:
print('Change the end parameter', end=':-)')

Change the end parameter:-)

## Attributes and Methods

An object in Python has attributes and methods

- **attributes:** a property of the object, some piece  of information about it
- **methods:** a procedure associated with an object, so it is an action where the main ingredient is the object itself

Check in: Make a diagram like the cat one, but for fish.

Numpy arrays have many methods and attributes. For example:

In [24]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [27]:
# T is an example of an attribute, it returns the transpose of an array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [29]:
type(a.T)

numpy.ndarray

In [31]:
# Shape is another attribute that tells us about the shape of the array
print(a.shape)

(2, 3)


In [34]:
# Ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type', type(a.ndim) )

dim: 2 | type <class 'int'>


Attributes can have many different data types.

Some examples of methods:

In [37]:
# Min method returns minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [39]:
# Run min method without axis
a.min()

1

In [40]:
# Parameter axis is optional


Remember, methods are functions associated with an object. We can confirm this!

In [42]:
# method to list() transform array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [45]:
type(a.tolist)

builtin_function_or_method

In [52]:
# Exercise
?print

Object `sep` not found.


Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


1. It is an optional argument because it is listed as such
2. 

In [58]:
var1 = 77

var2 = '99'

print(var1, var2, var1, sep='%')

77%99%77
